dag: simple_workflow
steps:
  generate_scores: {}

  filter_passing_scores:
    inputs:
      grades: output:generate_scores
    parameters:
      passing_score: 7
    depends_on: 
      - generate_scores